import { Montserrat } from 'next/font/google'
import './globals.css'
import { Navigation } from '@/components/Navigation'

import styled from 'styled-components'

const inter = Montserrat({subsets: ['cyrillic'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <Navigation />
          <main>
            {children}
          </main>
        </body>
    </html>
  )
}
